### ISSUE TITLE
Submission : DSL +  secondary task

### ISSUE THREAD

**Issue by kosenhitatchi** [vvv18-kinematics/assignment_inverse-kinematics-kosenhitatchi#1]
It's now working. 14 points on the off-line smoke-test

**Comment by pattacini** [comment]
That's great! 🎖 
Just started off the grading machine. Wait 5 minutes and check the gradebook!

**Comment by kosenhitatchi** [comment]
I added new gains for faster convergence.

**Comment by kosenhitatchi** [comment]
I was getting 14 locally but only got 6 remotely. Your VM might have run slow when your runned the evaluation.  I added new gains for a faster convergence.

**Comment by pattacini** [comment]
@kosenhitatchi actually your latest commit is failing...

**Comment by kosenhitatchi** [comment]
@pattacini : I'll come to you at the break to figure it out.
As it's working on my side 🤖

**Comment by pattacini** [comment]
It's fine now; there's been a glitch on the grading machine related to the yarplogger, apparently.
